sudo: required
services:
  - docker
before_install:
  - docker build -t mrzdtydlntm/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true mrzdtydlntm/react-test npm test
after_success:
  - docker build -t mrzdtydlntm/multi-client ./client
  - docker build -t mrzdtydlntm/multi-nginx ./nginx
  - docker build -t mrzdtydlntm/multi-server ./server
  - docker build -t mrzdtydlntm/multi-worker ./worker
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push mrzdtydlntm/multi-client
  - docker push mrzdtydlntm/multi-nginx
  - docker push mrzdtydlntm/multi-server
  - docker push mrzdtydlntm/multi-worker