version: '3.8'
services:
  api:
    build: 
      context: ./server #specify exact dir that we want Docker to use to build our image out
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    volumes:
      - /var/www/node_modules
      - ./server:/var/www
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    stdin_open: true
    volumes:
      - /var/www/node_modules
      - ./client:/var/www
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - api
      - client
    ports:
      - '3050:80'
    restart: always
  postgres:
    environment:
      - POSTGRES_PASSWORD=postgres_password
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /var/www/node_modules
      - ./worker:/var/www